apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oa2proxy-hrel
  namespace: oa2proxy
spec:
  interval: 1m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oa2proxy-hrep
        namespace: oa2proxy
      interval: 1m
  values:
    config:
      clientID: "oa2proxy"
      clientSecret: "vf0GPf7BZcRFV9kcwU7rMXyaDCrks4nP"
      # cookieSecret: "XXXXXXXXXXXXXXXX"