apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
spec:
  replicas: 1
  
    spec:
      containers:
      - args:
        - controller
        env:
        - name: MINIO_CONSOLE_TLS_ENABLE
          value: "off"
        - name: OPERATOR_STS_ENABLED
          value: "off"
        image: minio/operator:v6.0.3
        imagePullPolicy: IfNotPresent
        name: minio-operator
        resources:
          requests:
            cpu: 200m
            ephemeral-storage: 500Mi
            memory: 256Mi
