apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/minio/docs/master/source/extra/examples/minio-dev.yaml
  
# patchesStrategicMerge:
  # - deployment_patch.yaml



  # 
  # - helmrep.yaml
  # - minio-operator.yaml
  # - minio-tenant.yaml
  # - CRB.yaml
  # - svc.yaml