apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 1m
  chart:
    spec:
      chart: minio-operator
      sourceRef:
        kind: HelmRepository
        name: minio-rep
        namespace: flux-system
      interval: 1m