apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http-console
      targetPort: 9001
      protocol: TCP
    - port: 9000
      name: storage
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio