apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: clusterissuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
          serviceType: ClusterIP