apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    CREATE ROLE keycloak_usr WITH LOGIN CREATEDB CREATEROLE;
    ALTER USER keycloak_usr WITH PASSWORD 'kk123';
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE "keycloak" to keycloak_usr;