apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    CREATE DATABASE main;
    CREATE DATABASE keycloak;
    CREATE USER keycloak_user WITH PASSWORD '${KK_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak_user;
    DROP DATABASE admuser;