apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.5
        env:
          - name: POSTGRES_USER
            value: "mpm"
          - name: POSTGRES_PASSWORD
            value: "mpm123"
          - name: POSTGRES_DB
            value: ""  # Оставьте пустым, чтобы избежать создания БД с именем пользовател
          - name: PGDATA
            value: /var/lib/postgresql/data/data/
        ports:
          - containerPort: 5432
            name: postgres-port
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql/data/
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: storage
                operator: NotIn
                values:
                - no


  volumeClaimTemplates:
  - metadata:
      name: postgresdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "db"
      resources:
        requests:
          storage: 1Gi