apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.5
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password

          - name: KK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: kk-password

          - name: POSTGRES_DB
            value: ""  # Оставьте пустым, чтобы избежать создания БД с именем пользовател
          
          - name: PGDATA
            value: /var/lib/postgresql/data/data/

        # command: ["sh", "-c"]
        # args:
        #   - |
        #     psql -U postgres <<-EOSQL
        #       CREATE DATABASE keycloak;
        #       CREATE USER keycloak_user WITH PASSWORD '\$KK_PASSWORD';
        #       GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak_user;
        #     EOSQL


        ports:
          - containerPort: 5432
            name: postgres-port
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql/data/

      nodeSelector:
        storage: "yes"


  volumeClaimTemplates:
  - metadata:
      name: postgresdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "db"
      resources:
        requests:
          storage: 1Gi