apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 0m30s
  path: ./clusters/my-cluster/infrastucture/cert-manager
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system