apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: exapp
  namespace: flux-system
spec:
  interval: 0m30s
  path: ./clusters/my-cluster/apps/promoexapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system