apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 0m30s
  path: ./clusters/my-cluster/infrastucture/headlamp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system