apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 0m20s
  path: ./clusters/my-cluster/apps/lern
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system