apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lernapp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/my-cluster/apps/lern
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system