apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  interval: 0m30s
  path: ./clusters/my-cluster/monitoring/loki-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system