apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./clusters/my-cluster/infrastucture/longhorn
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system