apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 1m00s
  path: ./clusters/my-cluster/infrastucture/oauth2-proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system