apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/my-cluster/infrastucture/pgadm
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system