apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/my-cluster/infrastucture/psql
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system