apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometeus
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./clusters/my-cluster/monitoring/prometeus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system