apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./clusters/my-cluster/infrastucture/reflector
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system