apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kuberklustersecrets
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/MihalkaProMuzon/kuberklustersecrets

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: kuberklustersecrets
  path: ./
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age