apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lern-ingr
  annotations:
    nginx.ingress.kubernetes.io/auth-type: "openid"
    nginx.ingress.kubernetes.io/auth-openid-issuer: "http://keycloak:8080/realms/GAuth"
    nginx.ingress.kubernetes.io/auth-openid-client-id: "lernapp"
    nginx.ingress.kubernetes.io/auth-openid-client-secret: "nKYF4jZ9ANj6GTCEOC8SEnLj69dLM0gU"
    nginx.ingress.kubernetes.io/auth-openid-redirect-uri: "http://komplikter.servehttp.com/*"

  # annotations:
    # nginx.ingress.kubernetes.io/auth-url: "http://komplikter-sub1.servehttp.com/auth/realms/GAuth/protocol/openid-connect/userinfo"
    # nginx.ingress.kubernetes.io/auth-signin: "http://komplikter-sub1.servehttp.com/auth/realms/GAuth/protocol/openid-connect/auth?client_id=lernapp&redirect_uri=$request_uri&response_type=code"
spec:
  tls:
    - hosts:
      - komplikter.servehttp.com
      secretName: tlss-prod-secret
  ingressClassName: nginx
  rules:
    - host: komplikter.servehttp.com
      http:
        paths:
          - path: /phpapp
            pathType: Prefix
            backend:
              service:
                name: learn-app-svc
                port:
                  number: 443