apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lern-ingr
  # annotations:
    # cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: kompik.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80