apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oa2proxy-hrel
spec:
  interval: 0m15s
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oa2proxy-hrep
        namespace: flux-system
      interval: 1m
  values:  
    config:
      clientID: "lernapp"
      clientSecret: "YgxIyk5ltprcJMfPdq8SrH6Z97T5dF2v"
      cookieSecret: "S2JQRWJVVytudDJoTytmSjh5aWJOcEJaRXY2MS9ZZXM="
      # // For Keycloak versions <17: oidc-issuer-url=https://<keycloak host>/auth/realms/<your realm>
      configFile: |-
        provider="keycloak-oidc"
        redirect_url="https://komplikter.servehttp.com/oauth2/callback"
        oidc_issuer_url="https://komplikter-sub1.servehttp.com/realms/kuberkluster"
        email_domains = ["*"]
        code_challenge_method="S256"

    service:
      enabled: true
      type: ClusterIP

    ingress:
      enabled: true
      path: /oauth2
      pathType: Prefix
      className: nginx
      hosts:
        - komplikter.servehttp.com
      tls:
        - hosts:
          - komplikter.servehttp.com
          secretName: tlss-prod-secret
