apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oa2proxy-hrel
spec:
  interval: 1m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oa2proxy-hrep
        namespace: flux-system
      interval: 1m
  values:    
    config:
      clientID: "lernapp"
      clientSecret: "kz38gFWakiOub5rJ6Unv30kdefe4lkTV"
      cookieSecret: "qULOJLEHUMcNWRch-KUjSty6k3o-WG32j3EVIoQW3s4="
      provider: "kecloak"
      upstreams: 
        - "http://learn-app:80"
      redirectURI: "http://your-oauth2-proxy:port/oauth2/callback"
      emailDomains: ["*"]
      enableBasicAuth: false
      setXAuthRequest: true

    ingress:
      enabled: true
      hosts:
        - host: komplikter.servehttp.com
          paths:
            - /
      pathType: Prefix

    service:
      enabled: true
      type: ClusterIP