apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oa2proxy-hrel
spec:
  interval: 1m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oa2proxy-hrep
        namespace: flux-system
      interval: 1m
  values:  
    extraEnvVars: [
      "OAUTH2_PROXY_PROVIDER=keycloak-oidc"
    ]
  #     - name: OAUTH2_PROXY_CLIENT_ID
  #     value: "lernapp"
  #     - name: OAUTH2_PROXY_CLIENT_SECRET
  #     value: "vfgt5VJ81mffCxLW4xIfn9DE0KVu9USE"
  #     - name: OAUTH2_PROXY_REDIRECT_URL
  #     value: "https://komplikter.servehttp.com/oauth2/callback"
  #     - name: OAUTH2_PROXY_OIDC_ISSUER_URL
  #     value: "https://komplikter-sub1.servehttp.com/realms/kuberkluster"
  #     - name: OAUTH2_PROXY_EMAIL_DOMAIN
  #     value: "komplikter.servehttp.com"
  #     - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
  #     value: "S256"
    # --redirect-url=https://internal.yourcompany.com/oauth2/callback
    # --oidc-issuer-url=https://<keycloak host>/realms/<your realm> // For Keycloak versions <17: --oidc-issuer-url=https://<keycloak host>/auth/realms/<your realm>
    # --email-domain=<yourcompany.com> // Validate email domain for users, see option documentation

    service:
      enabled: true
      type: ClusterIP