apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oa2proxy-hrel
spec:
  interval: 0m15s
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oa2proxy-hrep
        namespace: flux-system
      interval: 1m
  values:  
    config:
      clientID: "lernapp"
      clientSecret: "vfgt5VJ81mffCxLW4xIfn9DE0KVu9USE"
      cookieSecret: "S2JQRWJVVytudDJoTytmSjh5aWJOcEJaRXY2MS9ZZXM="
      # // For Keycloak versions <17: oidc-issuer-url=https://<keycloak host>/auth/realms/<your realm>
      configFile: |-
        provider="keycloak-oidc"
        redirect_url="https://komplikter.servehttp.com/oauth2/callback"
        oidc_issuer_url="https://komplikter-sub1.servehttp.com/realms/kuberkluster"
        email_domains = ["*"]
        code_challenge_method="S256"

    # client_id="lernapp"
    # client_secret="vfgt5VJ81mffCxLW4xIfn9DE0KVu9USE"

    # provider = "keycloak-oidc"
    # provider_display_name = "Keycloak"
    # oidc_issuer_url = "https://komplikter-sub1.servehttp.com/realms/kuberkluster"
    # redirect_url="https://komplikter.servehttp.com/oauth2/callback"
    # email_domains = [ "*" ]
    # scope = "openid profile email"
    # pass_authorization_header = true
    # pass_access_token = true
    # pass_user_headers = true
    # set_authorization_header = true
    # set_xauthrequest = true
    # cookie_refresh = "1m"
    # cookie_expire = "30m"

    # config: 
    #   configFile: |
    #     email_domains = [ "*" ]
    #     code_challenge_method=S25
    #     provider=keycloak-oidc
    #     redirectUrl=https://komplikter.servehttp.com/oauth2/callback
    #     oidcIssuerUrl=https://komplikter-sub1.servehttp.com/realms/kuberkluster
    #     provider=keycloak-oidc
    #     clientID=
    #     clientSecret=

  #     - name: OAUTH2_PROXY_CLIENT_ID=lernapp
  #     value: "lernapp"
  #     - name: OAUTH2_PROXY_CLIENT_SECRET=vfgt5VJ81mffCxLW4xIfn9DE0KVu9USE
  #     value: "vfgt5VJ81mffCxLW4xIfn9DE0KVu9USE"
  #     - name: OAUTH2_PROXY_REDIRECT_URL=https://komplikter.servehttp.com/oauth2/callback
  #     value: "https://komplikter.servehttp.com/oauth2/callback"
  #     - name: OAUTH2_PROXY_OIDC_ISSUER_URL=https://komplikter-sub1.servehttp.com/realms/kuberkluster
  #     value: "https://komplikter-sub1.servehttp.com/realms/kuberkluster"
  #     - name: OAUTH2_PROXY_EMAIL_DOMAIN=komplikter.servehttp.com
  #     value: "komplikter.servehttp.com"
  #     - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
  #     value: "S256"
    # --redirect-url=https://internal.yourcompany.com/oauth2/callback
    # --oidc-issuer-url=https://<keycloak host>/realms/<your realm> // For Keycloak versions <17: --oidc-issuer-url=https://<keycloak host>/auth/realms/<your realm>
    # --email-domain=<yourcompany.com> // Validate email domain for users, see option documentation

    service:
      enabled: true
      type: ClusterIP

    ingress:
      enabled: true
      path: /oauth2
      pathType: Prefix
      className: nginx
      hosts:
        - komplikter.servehttp.com
      tls:
        - hosts:
          - komplikter.servehttp.com
          secretName: tlss-prod-secret
