apiVersion: v1
kind: Service
metadata:
  name: learn-app-svc
spec:
  selector:
    app: learn-app
  ports:
    - name: learn-app-lisner
      protocol: TCP
      port: 443
      targetPort: 80
  type: ClusterIP