apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-hrel
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki-stack
      version: '0.24.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-rep
        namespace: flux-system
      interval: 1m
   valuesFrom:
    - kind: ConfigMap
      name: hvalues
    