apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-rep
        namespace: monitoring
      interval: 1m
      
  values:
    lokiCanary:
      enabled: false
    test:
      enabled: false

    loki:
      commonConfig:
        replication_factor: 1

      auth_enabled: false
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      querier:
        max_concurrent: 3

      storage:
        type: s3
        bucketNames:
          chunks: "ls-chunks"
          ruler: "ls-ruler"
          admin: "ls-admin"
        s3:
          # s3 URL can be used to specify the endpoint, access key, secret key, and bucket name
          # s3: s3://access_key:secret_access_key@custom_endpoint/bucket_name
          endpoint: http://minio-svc.minio.svc.cluster.local:9000
          region: Skibidi
          accessKeyId: 5DJz6sM0TmAaRDUdSkVV
          secretAccessKey: RMykXg6Xjb6elu9IAPpWrArwx2oDaDZ3ILaZrVnR
          signatureVersion: v4
          s3ForcePathStyle: true
          insecure: true
          # HTTP configuration settings
          # http_config: {}

    deploymentMode: SimpleScalable

    backend:  
      replicas: 2
      nodeSelector: 
        storage: "yes"
      persistence:
        size: 200Mi
        storageClass: minidata
    chunksCache:
      enabled: false
      nodeSelector: 
        storage: "yes"
      persistence:
        enabled: false
        storageSize: 200Mi
        storageClass: minidata
    read:
      replicas: 1
      persistence:
        size: 200Mi
        storageClass: minidata
      nodeSelector: 
        storage: "yes"
    write:
      replicas: 1
      nodeSelector: 
        storage: "yes"
      persistence:
        size: 200Mi
        enabled: true
        storageClass: minidata

    # Disable minio storage
    minio:
      enabled: false

    # Zero out replica counts of other deployment modes
    singleBinary:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0