apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kk
  # annotations:
    # cert-manager.io/issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - keycloak.local
      secretName: tlss-secret
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-lb
                port:
                  number: 443