apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      nodeSelector:
        kubernetes.io/hostname: masterlocal
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:25.0.4
        args: ["start-dev"]
        ports:
        - containerPort: 8080
        env:
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres-clusterip:5432/keycloak_db"
        
        - name: KC_DB_USERNAME
          value: "keycloak_user"
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kk-secret
              key: KC_DB_PASSWORD
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: kk-secret
              key: keycloak-admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kk-secret
              key: keycloak-admin-pass

        # readinessProbe:
        #   httpGet:
        #     path: /auth
        #     port: 8080
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 5