apiVersion: apps/v1
kind: Deployment

metadata:
  name: flaskapp-dep

  labels:
    app: flaskapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp

  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      serviceAccountName: flask-app-sa
      containers:
      - name: flaskapp-container
        image: mihalkapromzona/flaga:hlt2
        ports:
        - containerPort: 5000
        env:
          - name: KK_SERVER_URL
            value: "https://komplikter-sub1.servehttp.com"
          - name: KK_CLIENT_ID
            value: "flaskapp"
          - name: KK_REALM_NAME
            value: "kuberkluster"
          # - name: HOST_URL
          #   value: "https://komplikter-sub2.servehttp.com"
          - name: KK_CLIENT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: kk_client_secret