apiVersion: apps/v1
kind: Deployment

metadata:
  name: flaskapp-dep

  labels:
    app: flaskapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp

  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      serviceAccountName: flaskapp-sa
      containers:
      - name: flaskapp-container
        image: mihalkapromzona/flaga:r1.2
        ports:
        - containerPort: 5000
        env:
          - name: KK_SERVER_URL
            value: "https://komplikter-sub1.servehttp.com"

          - name: GRAFANA_URL
            value: "https://komplikter-sub1.servehttp.com"
          - name: GRAFANA_USER
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: grafana-user
          - name: GRAFANA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: grafana-password

          - name: APP_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: app-secret-key

          - name: KK_CLIENT_ID 
            value: "flaskapp"
          - name: KK_REALM_NAME
            value: "kuberkluster"
          - name: KK_CLIENT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: kk-client-secret-key

          - name: HEADLAMP_TOKEN
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: headlamp-token

            