apiVersion: v1
kind: ServiceAccount
metadata:
  name: flaskapp-sa
  namespace: flaskapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flaskapp-role
  namespace: flaskapp
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokens"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flaskapp-rolebinding
  namespace: flaskapp
subjects:
  - kind: ServiceAccount
    name: flaskapp-sa
    namespace: flaskapp
roleRef:
  kind: Role
  name: flaskapp-role
  apiGroup: rbac.authorization.k8s.io
