apiVersion: v1
kind: ConfigMap
metadata:
  name: headlamp-oidc-config
  namespace: your-namespace
data:
  oidc.yaml: |
    clientID: "hedlampa"
    clientSecret: "J6iH1wq3987TY6CX3H8g7KGGOX8FZIvM"
    issuerURL: "http://192.168.0.240/realms/hdlmp"
    scopes: "email,profile"