apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: headlamp
      version: '0.24.0'
      sourceRef:
        kind: HelmRepository
        name: headlamp-rep
        namespace: flux-system
      interval: 1m
  values: 
    config:
      oidc:
        clientID: "hedlampa"
        clientSecret: "J6iH1wq3987TY6CX3H8g7KGGOX8FZIvM"
        issuerURL: "http://192.168.0.240/realms/hdlmp"
        scopes: "profile, email, profile"
    service:
      type: LoadBalancer