apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-rep
        namespace: monitoring
      interval: 1m
  values:
    persistence:
      enabled: true
      storageClassName: minidata
      size: 2Gi

    adminUser: admin
    adminPassword: 8iobO05xZHme40fnusUIWbhc1IlADaUwF83WH3XL

    nodeSelector:
      storage: "yes"

    service:
      port: 443

    # smtp:


    ## Override the deployment namespace
    ##
    # namespaceOverride: ""