---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin-pvc
spec:
  storageClassName: "data"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
      - name: busibox
        image: busybox:1.34.1
        imagePullPolicy: IfNotPresent
        command:
          - 'sh'
          - '-c'
          - 'chown 5050:5050 /tmp/mount'
        volumeMounts:
          - mountPath: /tmp/mount
            name: state
      containers:
      - name: pgadminz
        image: dpage/pgadmin4:6.14
        ports:
          - containerPort: 80
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "admin@example.com"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "admin"
        volumeMounts:
          - mountPath: /var/lib/pgadmin
            name: state
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: pgadmin-pvc

      nodeSelector:
        storage: "yes"