apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cissuer-letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: ma.foshin@mail.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cissuer-letsencrypt-prod-secret
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx