apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml

- clusterissuer.yaml
- komplikter-tls.yaml

- clusterissuer-prod.yaml
- komplikter-tls-prod.yaml
- komplikter-ydns-tls-prod.yaml