apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/deploy/longhorn.yaml
- nodes.yaml
- storageClass.yaml
- ingress-to-front.yaml