apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-master
  namespace: default
  annotations:
    nginx.org/mergeable-ingress-type: "master"
    # cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: komplikter.servehttp.com