apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-to-front
spec:
  ingressClassName: nginx
  rules:
    - host: komplikter.servehttp.com
      http:
        paths:
          - path: /pg
            pathType: Prefix
            backend:
              service: 
                name: pgadmin-svc
                port:
                  number: 80