apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory 
    privateKeySecretRef:
      name: letsencrypt-issuer-acc-key
    solvers:
    - http01:
       ingress:
         class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: lern
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  commonName: "carloshost.ydns.eu"
  dnsNames:
  - "carloshost.ydns.eu"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lern-app-ingress
  namespace: lern
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "carloshost.ydns.eu"
    secretName: tls-secret
  rules:
  - host: "carloshost.ydns.eu"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: learn-app-svc-o1
            port:
              number: 80