apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: carloshost-ydns-eu
  namespace: default
spec:
  secretName: kubeked-secret
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - mpm-co
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - kubeked.duckdns.org
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
