apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # адрес Let's Encrypt сервер
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ma.foshin@mail.ru  # ваш email
    privateKeySecretRef:
      name: letsencrypt-staging  # имя секрета для хранения приватного ключа
    solvers:
    - http01:
        ingress:
          class: nginx  # используем nginx ingress