apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 1m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: oauth2-proxy
      interval: 1m
  values:
    global:
      defaultStorageClass: "minidata"
      storageClass: "minidata"
