apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-to-front
  namespace: longhorn-system
  annotations:
    # cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: komplikter.servehttp.com
      http:
        paths:
          - path: /lg(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80