apiVersion: v1
kind: Node
metadata:
  name: masterlocal
  labels:
    storage: 'no'
---
apiVersion: v1
kind: Node
metadata:
  name: workerlocal
  annotations:
    node.longhorn.io/default-node-tags: '["db", "data"]'
    node.longhorn.io/default-disks-config: '[{"name":"data","path":"/var/lib/longhorn/","allowScheduling":true,"tags":["dataDisk"]}]'
  labels:
    node.longhorn.io/create-default-disk: 'config'
    storage: 'yes'

---
apiVersion: v1
kind: Node
metadata:
  name: workerlocal2
  annotations:
    node.longhorn.io/default-node-tags: '["data", "db"]'
    node.longhorn.io/default-disks-config: '[{"name":"data","path":"/var/lib/longhorn/","allowScheduling":true,"tags":["dataDisk"]}]'
  labels:
    node.longhorn.io/create-default-disk: 'config'
    storage: 'yes'