kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: data
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "120"
  fromBackup: ""
  nodeSelector: "data"
  diskSelector: "dataDisk"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: minidata
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "120"
  fromBackup: ""
  nodeSelector: "data"
  diskSelector: "dataDisk"