apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.240-192.168.0.280

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2simple
  namespace: metallb-system
spec:
  ipAddressPools:
  - default