apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  path: ./metallb
  prune: false
  targetNamespace: metallb-system
resources:
  - github.com/metallb/metallb/config/native?ref=v0.14.8
  - config.yaml